apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    cloud.googleapis.com/location: {{ .Values.region }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "{{ .Values.maxScale }}"
        autoscaling.knative.dev/minScale: "{{ .Values.minScale }}"
    spec:
      containers:
        - image: {{ .Values.image | default "us-docker.pkg.dev/cloudrun/container/hello" }}
        {{- if .Values.ports }}
          ports:
{{ toYaml .Values.ports | indent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
          startupProbe:
{{ toYaml .Values.startupProbe | indent 10 }}
        {{- end }}
        {{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 10 }}
        {{- end }}
        {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}