project: your-project-name
name: cloud-run-with-helm
minScale: "1"
maxScale: "25"
annotations:
  run.googleapis.com/ingress: all
ports:
  - containerPort: 8080
    name: http1
    protocol: TCP
livenessProbe:
  httpGet:
    path: "/healthy"
startupProbe:
  tcpSocket:
    port: 80
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "0.5Gi"